<?php

namespace App\Models\bitacorasalmacen;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class bitacoraModel extends Model
{
    protected $primaryKey = 'ID_BITACORAS_ALMACEN';
    protected $table = 'bitacorasalmacen';
    protected $fillable = [


        'RECEMPLEADO_ID',
        'INVENTARIO_ID',
        'SOLICITANTE_SALIDA',
        'FECHA_ALMACEN_SOLICITUD',
        'DESCRIPCION',
        'CANTIDAD',
        'CANTIDAD_SALIDA',
        'INVENTARIO',
        'FUNCIONAMIENTO_BITACORA',
        'OBSERVACIONES_REC',
        'RECIBIDO_POR',
        'ENTREGADO_POR',
        'FIRMA_RECIBIDO_POR',
        'FIRMA_ENTREGADO_POR',
        'OBSERVACIONES_BITACORA',
        'ACTIVO',
        'UNIDAD_SALIDA',
        /* =========================
           CONSUMIBLES
        ========================= */
        'FINALIZAR_BITACORA_CONSUMBIBLES',

        /* =========================
           RETORNABLE
        ========================= */
        'RETORNO_BITACORA_RETORNABLE',
        'FIRMA_RETORNADO_POR',
        'FIRMA_ACEPTADO_POR',
        'FECHA_RETORNO_BITACORA',

        /* =========================
           VEHICULO
        ========================= */
        'SEGUIMIENTO_VEHICULOS',
        'INSPECCION_USUARIO_VEHICULOS',
        'MARCA_VEHICULO',
        'MANTENIMIENTO_VEHICULO',
        'MODELO_VEHICULO',
        'COLOR_VEHICULO',
        'PLACAS_VEHICULO',
        'NOINVENTARIO_VEHICULO',
        'NOLICENCIA_VEHICULO',
        'FECHAVENCIMIENTO_VEHICULO',
        'TARJETA_CIRCULACION_VEHICULOS',
        'OBS_TARJETA_CIRCULACION_VEHICULOS',
        'TENENCIA_VIGENTE_VEHICULOS',
        'OBS_TENENCIA_VIGENTE_VEHICULOS',
        'POLIZA_SEGURO_VIGENTE_VEHICULOS',
        'OBS_POLIZA_SEGURO_VIGENTE_VEHICULOS',
        'INSTRUCTIVO_MANUAL_VEHICULOS',
        'OBS_INSTRUCTIVO_MANUAL_VEHICULOS',
        'ENCENDIDO_MOTOR_VEHICULOS',
        'ACCESORIOS_CAMBIO_LLANTA_VEHICULOS',
        'NIVEL_ACEITE_VEHICULOS',
        'REFLEJANTES_SEGURIDAD_VEHICULOS',
        'FRENOS_VEHICULOS',
        'CABLE_PASA_CORRIENTE_VEHICULOS',
        'SISTEMA_ELECTRICO_VEHICULOS',
        'GEL_ANTIBACTERIAL_VEHICULOS',
        'FAROS_VEHICULOS',
        'ESPEJOS_VEHICULOS',
        'INTERMITENTES_VEHICULOS',
        'CRISTALES_VENTANAS_VEHICULOS',
        'FUNCIONAMIENTO_LIMPIADORES_VEHICULOS',
        'MANCHAS_VESTIDURAS_VEHICULOS',
        'AGUA_LIMPIADORES_VEHICULOS',
        'ASIENTOS_VEHICULOS',
        'MOLDURAS_DELANTERAS_VEHICULOS',
        'CINTURONES_SEGURIDAD_VEHICULOS',
        'MOLDURAS_TRASERAS_VEHICULOS',
        'CALCOMANIAS_LOGO_VEHICULOS',
        'LLANTAS_VEHICULOS',
        'PASE_VEHICULAR_VEHICULOS',
        'LLANTA_REFACCION_VEHICULOS',
        'BRILLO_SEGURIDAD_VEHICULOS',
        'KILOMETRAJE_SALIDA_VEHICULOS',
        'COMBUSTIBLE_SALIDA_VEHICULOS',
        'NOPERSONAS_VEHICULOS',
        'HORASALIDA_VEHICULOS',
        'BOTIQUIN_PRIMEROS_AUXILIOS_VEHICULOS',
        'OBS_MALETIN_VEHICULOS',
        'OBS_FERULA_VEHICULOS',
        'OBS_FACE_SHIELD_VEHICULOS',
        'OBS_TIJERAS_VEHICULOS',
        'OBS_GASAS_10_VEHICULOS',
        'OBS_GUANTES_VEHICULOS',
        'OBS_MICROPORE_1_VEHICULOS',
        'OBS_MICROPORE_2_VEHICULOS',
        'OBS_VENDA_5_VEHICULOS',
        'OBS_VENDA_10_VEHICULOS',
        'OBS_SOLUCION_SALINA_VEHICULOS',
        'OBS_VENDA_TRIANGULAR_VEHICULOS',
        'KIT_SEGURIDAD_VEHICULOS',
        'OBS_MALETIN_HERRAMIENTAS_VEHICULOS',
        'OBS_DESARMADOR_CRUZ_VEHICULOS',
        'OBS_DESARMADOR_PLANO_VEHICULOS',
        'OBS_PINZAS_MULTIUSOS_VEHICULOS',
        'OBS_CUERDAS_BUNGEE_VEHICULOS',
        'OBS_LONA_POLIETILENO_VEHICULOS',
        'OBS_GUANTES_NEOPRENO_VEHICULOS',
        'OBS_CALIBRADOR_LLANTAS_VEHICULOS',
        'OBS_EXTINTOR_PQS_VEHICULOS',
        'OBS_LINTERNA_RECARGABLE_VEHICULOS',
        'OBS_GASAS_5_VEHICULOS',
        'KILOMETRAJE_LLEGADA_VEHICULOS',
        'COMBUSTIBLE_LLEGADA_VEHICULOS',
        'HORAREGRESO_VEHICULOS',
        'VERIFICA_POR',
        'FIRMA_VERIFICADO_POR',
        'VALIDADO_POR',
        'FIRMA_VALIDADO_POR',
        'RETORNO_VEHICULOS',
        'DANIOS_UNIDAD_JSON',
        'NUMERO_POLIZA',
        'ENTIDAD_POLIZA',
        'INICIOVIGENCIA_POLIZA',
        'FINVIGENCIA_POLIZA'




    ];
}