<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTableFormularioPpt extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('formulario_ppt', function (Blueprint $table) {
            $table->increments('ID_FORMULARO_PPT');
            $table->integer('USUARIO_ID')->nullable();
            $table->text('NOMBRE_PUESTO_PPT')->nullable();
            $table->text('NOMBRE_TRABAJADOR_PPT')->nullable();
            $table->text('AREA_TRABAJADOR_PPT')->nullable();
            $table->text('PROPOSITO_FINALIDAD_PPT')->nullable();
            $table->text('EDAD_PPT')->nullable();
            $table->text('EDAD_CUMPLE_PPT')->nullable();
            $table->text('GENERO_PPT')->nullable();
            $table->text('GENERO_CUMPLE_PPT')->nullable();
            $table->text('ESTADO_CIVIL_PPT')->nullable();
            $table->text('ESTADO_CIVIL_CUMPLE_PPT')->nullable();
            $table->text('NACIONALIDAD_PPT')->nullable();
            $table->text('NACIONALIDAD_CUMPLE_PPT')->nullable();
            $table->text('DISCAPACIDAD_PPT')->nullable();
            $table->text('DISCAPACIDAD_CUMPLE_PPT')->nullable();
            $table->text('CUAL_PPT')->nullable();
            $table->text('SECUNDARIA_PPT')->nullable();
            $table->text('SECUNDARIA_CUMPLE_PPT')->nullable();
            $table->text('TECNICA_PPT')->nullable();
            $table->text('TECNICA_CUMPLE_PPT')->nullable();
            $table->text('TECNICO_PPT')->nullable();
            $table->text('TECNICO_CUMPLE_PPT')->nullable();
            $table->text('UNIVERSITARIO_PPT')->nullable();
            $table->text('UNIVERSITARIO_CUMPLE_PPT')->nullable();
            $table->text('SITUACION_PPT')->nullable();
            $table->text('SITUACION_CUMPLE_PPT')->nullable();
            $table->text('CEDULA_PPT')->nullable();
            $table->text('CEDULA_CUMPLE_PPT')->nullable();
            $table->text('AREA1_PPT')->nullable();
            $table->text('AREA1_CUMPLE_PPT')->nullable();
            $table->text('AREA2_PPT')->nullable();
            $table->text('AREA2_CUMPLE_PPT')->nullable();
            $table->text('AREA3_PPT')->nullable();
            $table->text('AREA3_CUMPLE_PPT')->nullable();
            $table->text('AREA4_PPT')->nullable();
            $table->text('AREA4_CUMPLE_PPT')->nullable();
            $table->text('AREA_REQUERIDA_PPT')->nullable();
            $table->text('AREA_CONOCIMIENTOTRABAJADOR_PPT')->nullable();
            $table->text('EGRESADO_ESPECIALIDAD_PPT')->nullable();
            $table->text('GRADUADO_ESPECIALIDA_PPT')->nullable();
            $table->text('ESPECIALIDAD_CUMPLE_PPT')->nullable();
            $table->text('AREAREQUERIDA_CONOCIMIENTO_PPT')->nullable();
            $table->text('EGRESADO_MAESTRIA_PPT')->nullable();
            $table->text('GRADUADO_MAESTRIA_PPT')->nullable();
            $table->text('MAESTRIA_CUMPLE_PPT')->nullable();
            $table->text('EGRESADO_DOCTORADO_PPT')->nullable();
            $table->text('GRADUADO_DOCTORADO_PPT')->nullable();
            $table->text('DOCTORADO_CUMPLE_PPT')->nullable();
            $table->text('AREA_CONOCIMINETO_TRABAJADOR_PPT')->nullable();
            $table->text('WORD_APLICA_PPT')->nullable();
            $table->text('WORD_BAJO_PPT')->nullable();
            $table->text('WORD_MEDIO_PPT')->nullable();
            $table->text('WORD_ALTO_PPT')->nullable();
            $table->text('WORD_CUMPLE_PPT')->nullable();
            $table->text('EXCEL_APLICA_PPT')->nullable();
            $table->text('EXCEL_BAJO_PPT')->nullable();
            $table->text('EXCEL_MEDIO_PPT')->nullable();
            $table->text('EXCEL_ALTO_PPT')->nullable();
            $table->text('EXCEL_CUMPLE_PPT')->nullable();
            $table->text('POWER_APLICA_PPT')->nullable();
            $table->text('POWER_BAJO_PPT')->nullable();
            $table->text('POWER_MEDIO_PPT')->nullable();
            $table->text('POWER_ALTO_PPT')->nullable();
            $table->text('POWER_CUMPLE_PPT')->nullable();
            $table->text('NOMBRE_IDOMA1_PPT')->nullable();
            $table->text('APLICA_IDIOMA1_PPT')->nullable();
            $table->text('HABLAR_IDIOMA1_PPT')->nullable();
            $table->text('ESCRIBIR_IDIOMA1_PPT')->nullable();
            $table->text('LEER_IDIOMA1_PPT')->nullable();
            $table->text('ESCUCHAR_IDIOMA1_PPT')->nullable();
            $table->text('IDIOMA1_CUMPLE_PPT')->nullable();
            $table->text('NOMBRE_IDIOMA2_PPT')->nullable();
            $table->text('APLICA_IDIOMA2_PPT')->nullable();
            $table->text('ESCRIBIR_IDIOMA2_PPT')->nullable();
            $table->text('LEER_IDIOMA2_PPT')->nullable();
            $table->text('ESCUCHAR_IDIOMA2_PPT')->nullable();
            $table->text('IDIOMA2_CUMPLE_PPT')->nullable();
            $table->text('NOMBRE_IDIOMA3_PPT')->nullable();
            $table->text('APLICA_IDIOMA3_PPT')->nullable();
            $table->text('HABLAR_IDIOMA3_PPT')->nullable();
            $table->text('ESCRIBIR_IDIOMA3_PPT')->nullable();
            $table->text('LEER_IDIOMA3_PPT')->nullable();
            $table->text('ESCUCHAR_IDIOMA3_PPT')->nullable();
            $table->text('IDIOMA3_CUMPLE_PPT')->nullable();
            $table->text('EXPERIENCIA_LABORAL_GENERAL_PPT')->nullable();
            $table->text('EXPERIENCIAGENERAL_CUMPLE_PPT')->nullable();
            $table->text('CANTIDAD_EXPERIENCIA_PPT')->nullable();
            $table->text('CANTIDAD_EXPERIENCIA_CUMPLE_PPT')->nullable();
            $table->text('EXPERIENCIA_ESPECIFICA_PPT')->nullable();
            $table->text('EXPERIENCIA_ESPECIFICA_CUMPLE_PPT')->nullable();
            $table->text('PRACTICA_PROFESIONAL_PPT')->nullable();
            $table->text('PRACTICA_PROFESIONAL_CUMPLE_PPT')->nullable();
            $table->text('ELABORACION_REPORTES_PPT')->nullable();
            $table->text('ELABORACION_REPORTES_CUMPLE_PPT')->nullable();
            $table->text('AUXILIAR_ASISTENTE_PPT')->nullable();
            $table->text('AUXILIAR_ASISTENTE_CUMPLE_PPT')->nullable();
            $table->text('SUPERVISOR_COORDINADOR_PPT')->nullable();
            $table->text('SUPERVISOR_COORDINADOR_CUMPLE_PPT')->nullable();
            $table->text('ANALISTA_ESPECIALISTA_PPT')->nullable();
            $table->text('ANALISTA_ESPECIALISTA_CUMPLE_PPT')->nullable();
            $table->text('CONSULTOR_ASESOR_PPT')->nullable();
            $table->text('CONSULTOR_ASESOR_CUMPLE_PPT')->nullable();
            $table->text('TECNICO_MUESTREO_PPT')->nullable();
            $table->text('TECNICO_MUESTREO_CUMPLE_PPT')->nullable();
            $table->text('JEFE_AREA_PPT')->nullable();
            $table->text('JEFE_AREA_CUMPLE_PPT')->nullable();
            $table->text('SIGNATARIO_PPT')->nullable();
            $table->text('SIGNATARIO_CUMPLE_PPT')->nullable();
            $table->text('GERENTE_DIRECTOR_PPT')->nullable();
            $table->text('GERENTE_DIRECTOR_CUMPLE_PPT')->nullable();
            $table->text('TIEMPO_EXPERIENCIA_PPT')->nullable();
            $table->text('TIEMPO_EXPERIENCIA_CUMPLE_PPT')->nullable();
            $table->text('INNOVACION_REQUERIDA_PPT')->nullable();
            $table->text('INNOVACION_DESEABLE_PPT')->nullable();
            $table->text('INNOVACION_CUMPLE_PPT')->nullable();
            $table->text('PASION_REQUERIDA_PPT')->nullable();
            $table->text('PASION_DESEABLE_PPT')->nullable();
            $table->text('PASION_NO_REQUERIDA_PPT')->nullable();
            $table->text('PASION_CUMPLE_PPT')->nullable();
            $table->text('SERVICIO_CLIENTE_REQUERIDA_PPT')->nullable();
            $table->text('SERVICIO_CLIENTE_DESEABLE_PPT')->nullable();
            $table->text('SERVICIO_CLIENTE_NO_REQUERIDA_PPT')->nullable();
            $table->text('SERVICIO_CLIENTE_CUMPLE_PPT')->nullable();
            $table->text('COMUNICACION_EFICAZ_REQUERIDA_PPT')->nullable();
            $table->text('COMUNICACION_EFICAZ_DESEABLE_PPT')->nullable();
            $table->text('COMUNICACION_EFICAZ_NO_REQUERIDA_PPT')->nullable();
            $table->text('COMUNICACION_EFICAZ_CUMPLE_PPT')->nullable();
            $table->text('TRABAJO_EQUIPO_REQUERIDA_PPT')->nullable();
            $table->text('TRABAJO_EQUIPO_DESEABLE_PPT')->nullable();
            $table->text('TRABAJO_EQUIPO_NO_REQUERIDA_PPT')->nullable();
            $table->text('TRABAJO_EQUIPO_CUMPLE_PPT')->nullable();
            $table->text('INTEGRIDAD_REQUERIDA_PPT')->nullable();
            $table->text('INTEGRIDAD_DESEABLE_PPT')->nullable();
            $table->text('INTEGRIDAD_NO_REQUERIDA_PPT')->nullable();
            $table->text('INTEGRIDAD_CUMPLE_PPT')->nullable();
            $table->text('RESPONSABILIDAD_SOCIAL_REQUERIDA_PPT')->nullable();
            $table->text('RESPONSABILIDAD_SOCIAL_DESEABLE_PPT')->nullable();
            $table->text('RESPONSABILIDAD_SOCIAL_NO_REQUERIDA_PPT')->nullable();
            $table->text('RESPONSABILIDAD_SOCIAL_CUMPLE_PPT')->nullable();
            $table->text('ADAPTABILIDAD_REQUERIDA_PPT')->nullable();
            $table->text('ADAPTABILIDAD_DESEABLE_PPT')->nullable();
            $table->text('ADAPTABILIDAD_NO_REQUERIDA_PPT')->nullable();
            $table->text('ADAPTABILIDAD_CUMPLE_PPT')->nullable();
            $table->text('LIDERAZGO_REQUERIDA_PPT')->nullable();
            $table->text('LIDERAZGO_DESEABLE_PPT')->nullable();
            $table->text('LIDERAZGO_NO_REQUERIDA_PPT')->nullable();
            $table->text('LIDERAZGO_CUMPLE_PPT')->nullable();
            $table->text('TOMA_DECISIONES_REQUERIDA_PPT')->nullable();
            $table->text('TOMA_DECISIONES_DESEABLE_PPT')->nullable();
            $table->text('TOMA_DECISIONES_NO_REQUERIDA_PPT')->nullable();
            $table->text('TOMA_DECISIONES_CUMPLE_PPT')->nullable();
            $table->text('DISPONIBILAD_VIAJAR_PPT')->nullable();
            $table->text('REQUIERE_PASAPORTE_PPT')->nullable();
            $table->text('REQUIERE_VISA_PPT')->nullable();
            $table->text('REQUIERE_LICENCIA_PPT')->nullable();
            $table->text('CAMBIO_RESIDENCIA_PPT')->nullable();
            $table->text('DISPONIBILADVIAJAR_OPCION_PPT')->nullable();
            $table->text('DISPONIBILADVIAJAR_OPCION_CUMPLE')->nullable();
            $table->text('REQUIEREPASAPORTE_OPCION_PPT')->nullable();
            $table->text('REQUIEREPASAPORTE_OPCION_CUMPLE')->nullable();
            $table->text('REQUIERE_VISA_OPCION_PPT')->nullable();
            $table->text('REQUIEREVISA_OPCION_CUMPLE')->nullable();
            $table->text('REQUIERELICENCIA_OPCION_PPT')->nullable();
            $table->text('REQUIERELICENCIA_OPCION_CUMPLE')->nullable();
            $table->text('CAMBIORESIDENCIA_OPCION_PPT')->nullable();
            $table->text('CAMBIORESIDENCIA_OPCION_CUMPLE')->nullable();
            $table->text('OBSERVACIONES_PPT')->nullable();
            $table->text('ELABORADO_NOMBRE_PPT')->nullable();
            $table->text('ELABORADO_FIRMA_PPT')->nullable();
            $table->text('ELABORADO_FECHA_PPT')->nullable();
            $table->text('REVISADO_NOMBRE_PPT')->nullable();
            $table->text('REVISADO_FIRMA_PPT')->nullable();
            $table->text('REVISADO_FECHA_PPT')->nullable();
            $table->text('AUTORIZADO_NOMBRE_PPT')->nullable();
            $table->text('AUTORIZADO_FIRMA_PPT')->nullable();
            $table->text('AUTORIZADO_FECHA_PPT')->nullable();
            $table->timestamps();
            
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('formulario_ppt');
    }
}

